version: '3'
services:
    web:
        build: .
        links:
            - db
        ports:
            - "8000:8000"
        volumes:
            - .:/usr/src/tinylibrary
        environment:
            - DATABASE_URL=postgres://postgres@db:5432/postgres
            - DEBUG
    rollup:
        build:
            context: .
            dockerfile: rollup.Dockerfile
        volumes:
            - .:/usr/src/tinylibrary
            # - /usr/src/tinylibrary/node_modules
        command: rollup -wc
        tty: true

    db:
        image: postgres