# Generated by Django 2.0.5 on 2018-06-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinylibrary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ddc_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='lcc_section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
